name: "alboarrd-prod"

services:
  alboarrd:
    container_name: alboarrd-prod
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - ./config.yaml:/etc/config.yaml:ro
    working_dir: /app
    ports:
      - "3000"
    environment:
      - HEADER_USER=remote-user
      - HEADER_NAME=remote-name
      - HEADER_GROUPS=remote-group
