name: "links-prod"

services:
  links:
    container_name: links
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - ./config.yaml:/etc/config.yaml:ro
    working_dir: /app
    ports:
      - "3000"
